---
- name: restart elasticsearch
  monit:
    name=elasticsearch
    state=restarted
  sudo: yes

- name: restart logstash
  monit:
    name=logstash
    state=restarted
  sudo: yes

- name: restart kibana
  supervisorctl:
    name=kibana
    state=restarted
  sudo: yes
